// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPrXHmTqJ_BTXcm2h6g_FwIFFtuCyxEdY',
    appId: '1:664874135531:web:98ce43489c594354b0b3ae',
    messagingSenderId: '664874135531',
    projectId: 'bloom-and-bliss-4itd',
    authDomain: 'bloom-and-bliss-4itd.firebaseapp.com',
    storageBucket: 'bloom-and-bliss-4itd.firebasestorage.app',
    measurementId: 'G-9X6XCQFKYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAWpyQIYVZ-gWXxudqOWsrfUuDVw5d69k',
    appId: '1:664874135531:android:7624b3c5d73c868bb0b3ae',
    messagingSenderId: '664874135531',
    projectId: 'bloom-and-bliss-4itd',
    storageBucket: 'bloom-and-bliss-4itd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwcEf6TP8NaZRTNxD44C8SQtBYsjVjc9I',
    appId: '1:664874135531:ios:add4e7884591b21bb0b3ae',
    messagingSenderId: '664874135531',
    projectId: 'bloom-and-bliss-4itd',
    storageBucket: 'bloom-and-bliss-4itd.firebasestorage.app',
    iosBundleId: 'com.example.bloomAndBliss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwcEf6TP8NaZRTNxD44C8SQtBYsjVjc9I',
    appId: '1:664874135531:ios:add4e7884591b21bb0b3ae',
    messagingSenderId: '664874135531',
    projectId: 'bloom-and-bliss-4itd',
    storageBucket: 'bloom-and-bliss-4itd.firebasestorage.app',
    iosBundleId: 'com.example.bloomAndBliss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPrXHmTqJ_BTXcm2h6g_FwIFFtuCyxEdY',
    appId: '1:664874135531:web:c8c34d954595fcd5b0b3ae',
    messagingSenderId: '664874135531',
    projectId: 'bloom-and-bliss-4itd',
    authDomain: 'bloom-and-bliss-4itd.firebaseapp.com',
    storageBucket: 'bloom-and-bliss-4itd.firebasestorage.app',
    measurementId: 'G-Z9B0YF00KV',
  );
}
